### ISSUE TITLE
Error Connecting to Mongodb 3.2

### ISSUE THREAD

**Issue by gtskaushik** [mongo-js/mongojs#287]
I am not able to connect to mongodb 3.2 with mongojs 2.3.0.

But when I revert to 0.18 version of mongojs, I am able to connect

**Comment by saintedlama** [comment]
Could you add some code and error message?

**Comment by saintedlama** [comment]
Is this still an issue or did you manage to fix the problem?

**Comment by blabno** [comment]
It's still an issue. It happens to me when connecting to clustered mlab.com (heroku addon).

**Comment by leim** [comment]
I met this problem too. The mongodb server is version 3.2 and mongojs version is 1.3.0 and I came up with this situation.

`[ERROR-Server:18372] 1469004397953 [0] failed to authenticate against server 100.98.197.87:3717 { type: 'error',
  message: '[0] failed to authenticate against server 100.98.197.87:3717',
  className: 'Server',
  pid: 18372,
  date: 1469004397953 }
[ERROR-Server:18372] 1469004397954 [1] failed to authenticate against server 100.98.198.33:3717 { type: 'error',
  message: '[1] failed to authenticate against server 100.98.198.33:3717',
  className: 'Server',
  pid: 18372,
  date: 1469004397954 }`

**Comment by gbaladi** [comment]
I have this issue with mongo 3.2.9 and I solved setting { authMechanism: 'ScramSHA1' } option
