### ISSUE TITLE
Publish version with mongodb ^3

### ISSUE THREAD

**Issue by ghmeier** [mongo-js/mongojs#371]
Is there a reason the code on master hasn't been published? It'd be nice to have the version with the latest mongodb driver.

**Comment by mbroadst** [comment]
@mafintosh please consider making a release of your `master` which has already updated to mongodb 3.x. The 2.x version of the driver is no longer supported, and we have users of `mongojs` asking for help on our JIRA.

**Comment by henryoswald** [comment]
It would be great if this could get published

**Comment by saintedlama** [comment]
done
