### ISSUE TITLE
MongoDB Atlas's URI does not work

### ISSUE THREAD

**Issue by chroventer** [mongo-js/mongojs#378]

**Comment by saintedlama** [comment]
Could you provide a bit more detail? Version, anonymized URL

**Comment by chroventer** [comment]
> Could you provide a bit more detail? Version, anonymized URL

I am using the latest version of `Node.js` and `MongoJS` (v2.6.0) and the URI is used to connect to the cluster is `mongodb+srv://<username>:<password>@test-rhvos.mongodb.net/test?retryWrites=true&w=majority`.

However, when I pass this URI to the `MongoJS`, it returns an error: `[MongoError]: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017`.
I tried the same URI with the official driver and it worked perfectly fine.

**Comment by chroventer** [comment]
@saintedlama, could you take a look at the reply I sent?

**Comment by saintedlama** [comment]
Fixed in commit https://github.com/mafintosh/mongojs/commit/106af3ec16f72a71b705983c1f5c2ab680179ecb

**Comment by saintedlama** [comment]
Major version update 3.0.0 released to npm so that fix is available if you update the package
