### ISSUE TITLE
collection.update no longer usable for overwriting an entry

### ISSUE THREAD

**Issue by naugtur** [mongo-js/mongojs#381]
This used to work for insert or overwrite by criteria. 
```js
collection.update(criteria, data, { upsert: true }, cb)
```
Now mongodb native client throws if `data` is passed, but atomic operators won't overwrite an existing object. 

```js
collection.update({ id: 1 }, { $set: { id: 1, foo:"bar" } }, { upsert: true }, cb)
...
collection.update({ id: 1 }, { $set: { id: 1, notfoo:"bar" } }, { upsert: true }, cb)
...
collection.findOne({ id: 1 })
```
gets 
```js
 { id: 1, foo:"bar", notfoo:"bar"  }
```
Expected foo not to be there anymore

replaceOne should be used instead of updateOne internally in update to bring back the old behavior.  
I'm _not_ requesting bringing back the old behavior. 

Exposing `.replace` with logic similar to update would address this.

**Comment by naugtur** [comment]
I also noticed this:
https://github.com/mongo-js/mongojs/blob/master/lib/collection.js#L173

`.save` has exactly the same problem.

**Comment by saintedlama** [comment]
Please give me a hint, what is the expected outcome of the example above?

**Comment by naugtur** [comment]
Updated the issue.

**Comment by saintedlama** [comment]
Thanks for the update

I implemented a fix in https://github.com/mongo-js/mongojs/tree/replace-one could you take a look?

**Comment by naugtur** [comment]
Looks good to me.

For consistency and completeness of the library I'd go with exposing `.replace` that maps to replaceOne or replaceMany with the same exact logic as the `.update` one. 
But this definitely addresses my usecase so I'd be happy to get it as-is.

BTW. a note in readme or changelog on `.update` working differently would be useful. To hint people `$set` is not a good replacement - since we both fell for it, others will too :)

I was going to try to contribute next week at work, but you're too quick :)
 Thanks!

**Comment by wormggmm** [comment]
hi,
what is the issue meaning?
i try 2.4.1 and 3.0.0 of mongojs. they have the same situation.

the data in mongo before:
![image](https://user-images.githubusercontent.com/3104869/67838209-be840780-fb2b-11e9-9dee-1f7892e5d7be.png)

and then run:
```
const mongojs = require("mongojs");
var mongoUrl = "mongodb://root:bu5PequyEy7c@127.0.0.1:27017/test";
var mongodb = new mongojs(mongoUrl, ["mails"]);

mongodb.mails.update({_id:1},{"$set":{_id:1, a:1}}, {upsert:1}, function(){
     console.log("update finish!");
})
```
the data in mongo after:
![image](https://user-images.githubusercontent.com/3104869/67838319-030fa300-fb2c-11e9-838b-ce7714dbe540.png)

**Comment by naugtur** [comment]
@wormggmm 
note how in my example 2nd argument to update was originally just the data object, not a $set command. Older version would replace the object. New version won't accept a payload without $commands. and using $set doesn't fulfill the usecase.

**Comment by naugtur** [comment]
@saintedlama I reviewed your change carefully and my suggestion to add `.replace` doesn't add up since there's no replaceMany in mongodb. It's complete as-is.

Could you merge and release the branch? Anything I can help with?

**Comment by saintedlama** [comment]
Published 3.1.0 a minute ago

**Comment by naugtur** [comment]
Great! Thanks.

**Comment by maomaoguo2017** [comment]
@naugtur @saintedlama 
Does this mean that  "collection.update"  which is  without "$command",  should be replaced with "replaceOne"?
please look #384

**Comment by naugtur** [comment]
Yes.
The official mongodb client library underneath is not accepting plain objects as input to update despite mongo docs suggesting update could accept them. You need to switch to replaceOne

**Comment by maomaoguo2017** [comment]
@naugtur 
thanks for your time.  
I'm going to modify hundreds of this interface now. 
IT IS NOT COOL....

**Comment by naugtur** [comment]
It was an intentional change apparently
https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md#updateone--updatemany

You can report that to their Jira.

If find-and-replace is not enough for changing this in bulk (I believe it should be ok) you can use jscodeshift. My intro to it here: https://www.youtube.com/watch?v=Ly_J9Tqitn0

**Comment by maomaoguo2017** [comment]
@naugtur 
.update of mongodb is only deprecated, but it can be used. I think mongojs should not change the .update behavior, but only deprecated it. If mongodb removes the update interface one day, mongojs can throw an exception from mongodb. i think this is better.

mongodb v3.3
![image](https://user-images.githubusercontent.com/34433498/70798422-e41a5700-1de1-11ea-84f7-f96f23230dd8.png)

**Comment by maomaoguo2017** [comment]
@naugtur
thanks. i will watch the video.
